CREATE TABLE AllDatatypeColumns (
    varchar_column text PRIMARY KEY,
    tinyint_column int,
    text_column text,
    date_column date,
    smallint_column smallint,
    mediumint_column int,
    int_column int,
    bigint_column bigint,
    float_column float,
    double_column double,
    decimal_column decimal,
    datetime_column timestamp,
    timestamp_column timestamp,
    time_column time,
    year_column text,
    char_column text,
    tinytext_column text,
    mediumtext_column text,
    longtext_column text,
    enum_column text,
    bool_column boolean,
    other_bool_column boolean,
);